application: golang-static
version: 2
runtime: go
api_version: go1

handlers:

# if you want to use the dynamic one, comment off the static one
#- url: /
#  static_dir: static
- url: /.*
  script: _go_app